<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
	<span class="name"><?=$user->name?></span>
	<span class="caret"></span>
</a>
<ul class="dropdown-menu">
	<li><a href="<?=$this->url('profile', array('action'=>'view'));?>">Профиль</a></li>
	<li>
		<a href="#">Action</a>
	</li>
	<li>
		<a href="#">Another action</a>
	</li>
	<li>
		<a href="#">Something else here</a>
	</li>
	<li role="separator" class="divider"></li>
	<li><a href="<?=$logout_url?>"><span class="glyphicon glyphicon-log-out"></span>Выход</a></li>
</ul>