<div class="form-group">
   
	<?php echo $this->formRow($collection->get('id')); ?>
	<label class="control-label col-sm-2 col-md-2 col-lg-2"></label>
	<div class="input-group col-sm-7 col-md-6 col-lg-6"> 
		<p class="form-control-static">
			<a class="edit-role hover_show_icon" href="#" data-toggle="tooltip" data-placement="auto left" title="Редактировать роль">
				<span class="role_label"><?=$collection->get('label')->getValue()?></span>
				<span class="glyphicon glyphicon-pencil"></span>
			</a>
		</p>
		<span class="input-group-btn"> 
			<button type="button" class="btn btn-link role_cancel" data-toggle="tooltip" data-placement="auto right" title="Отменить роль"><span class="glyphicon glyphicon-remove"></span></button> 
		</span> 
	</div>
</div>