<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title">Modal title</h4>
		</div>
		<div class="modal-body">
			<div class="filter margin-bottom-40">

				<?php
				//$form = $this->filterForm;

				$this->filterForm->prepare();
				$this->filterForm->setAttribute('class', 'form-inline');
				echo $this->form()->openTag($this->filterForm);
					
				foreach($this->filterForm->get('filter') as $el):
				
				?>
				
					<?php if($el instanceof \Zend\Form\Element\Checkbox): 
						$el->setUseHiddenElement(false);
					?>
						<div class="checkbox">
							<label>
								<?php
									echo $this->formElement($el);
									echo $el->getLabel(); 
								?>
							</label>
						</div>
					<?php else: ?>
						<div class="form-group">
						<?php
							$el->setAttribute('class', 'form-control')
							->setAttribute('placeholder', $el->getLabel())
							->setAttribute('title', $el->getLabel())
							->setAttribute('data-toggle', "tooltip")
							->setAttribute('data-placement', "top");
							echo $this->formElement($el);
						?>
						</div>	
					<?php endif; ?>
				
				<?php endforeach; ?>
				
				<button type="submit" class="btn btn-default">Применить</button>
				
				<?php
				echo $this->form()->closeTag(); 
				?>

			</div>

			<table class="table">
				<tr>
					<th></th>
					<th>
						<a class="sortable <?=$sortLinks['name']['dir']?>" href="<?=$sortLinks['name']['url']?>" data-toggle="tooltip" title="Нажмите для сортировки">
							<?php echo $this->translate('page name');?>
							<span class="glyphicon glyphicon-sort-by-alphabet"></span>
							<span class="glyphicon glyphicon-sort-by-alphabet-alt"></span>
						</a>
					</th>
				</tr>
				<?php foreach ($this->paginator as $page) : ?>
					
					<tr <?=$page->isActive() ? '' : "class='inactive'"?>>
						<td>
							<input type="checkbox" name="pages[]" value="<?=$page->id?>">
						</td>
						<td>
							<a href="#<?=$page->id?>">
								<?= $this->escapeHtml($page->name);?>
							</a>
						</td>
					</tr>
				<?php endforeach; ?>
			</table>

			<?php
			echo $this->paginationControl(
				$this->paginator,
				'sliding',
				'application/pagination/paginator.phtml',
				array(
					'route' => $this->routName,
					'params' => $this->routeParams,
					'options' => $this->routeOptions
				)
			 );
			?>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Отменить</button>
			<button type="button" class="btn btn-primary">Выбрать</button>
		</div>
    </div>
</div>