<script src="/js/lib/tinymce/jquery.tinymce.min.js"></script>
<script>
    $(function() {
        tinymce.init({ selector:'textarea' });    
    });
</script>

<style>
	@media screen and (min-width: 1200px){
		.content{
			padding-left:6%;
		}
	}
		
	#permissions .form-inline .actions label{
		margin: 0 10px;
	}
</style>

<h1 class="page-header"><?=$title?></h1>

<?php
$form->prepare();
$form->setAttribute('class', 'form-horizontal')->setAttribute('role', 'form');
echo $this->message($message, $is_success);

echo $this->form()->openTag($form);
?>

<div class="col-lg-6">
</div>

<?php if(in_array('activeToggle', $allowedActions)): ?>
<div class="col-lg-6">
	<div class="form-group">
		<div class="checkbox padding-left-20 col-sm-offset-5 col-md-offset-3 col-lg-offset-5">
			<label class="">
			<?php 
				echo $this->formElement($form->get('is_active'));
				echo $form->get('is_active')->getLabel();
			?>
			</label>
		</div>
	</div>
</div>
<?php endif;?>

<div class="col-lg-6">
	<?php echo $this->formGroup()
		->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
		->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
		->render($form->get('name'));?>
</div>

<div class="col-lg-6">
	<?php echo $this->formGroup()
		->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
		->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
		->render($form->get('header'));?>
</div>

<div class="col-lg-6">
	<?php echo $this->formGroup()
		->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
		->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
		->render($form->get('title'));?>
</div>

<div class="col-lg-6">
	<?php echo $this->formGroup()
		->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
		->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
		->render($form->get('uri'));?>
</div>

<div class="clearfix"></div>

<div class="col-lg-12 content">
	<?php echo $this->formGroup()
		->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-2'))
		->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-10 col-lg-offset-2'))
		->render($form->get('content'));?>
</div>
<div class="clearfix"></div>
<div class="col-lg-6">
	<?php echo $this->formGroup()
		->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
		->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
		->render($form->get('descriotion'));?>
</div>

<div class="col-lg-6">
	<?php echo $this->formGroup()
		->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
		->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
		->render($form->get('keywords'));?>
</div>

<div class="clearfix"></div>

<?=$this->partial('pages/page/permissions.phtml', array('group'=>$form->get('group'), 'permissions'=>$form->get('permissions')));?>

<div class="clearfix visible-lg-block"></div>

<div class="form-group-fixed col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
	<?php if(in_array('del', $allowedActions)): ?>
		<div class="pull-left">
			<button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#ConfirmDelete" >Удалить</button>
		</div>
	<?php endif;?>
	<div class="pull-right">
		<button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#ConfirmCancel" >Отменить</button>
		<?php 
			$form->get('submit')->setAttribute('class','btn btn-primary btn-lg');
			echo $this->formElement($form->get('submit'));
		?>
	</div>
</div>



<?php echo $this->form()->closeTag(); ?>

<div class="modal fade" tabindex="-1" role="dialog" id="ConfirmCancel">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Вы уверены?</h4>
			</div>
			<div class="modal-body">
				<p>Вы уверены, что хотите закрыть форму? Несохранённые данные будут потеряны!</p>
			</div>
			<div class="modal-footer">
				<a href="<?=$referer?>" class="btn btn-danger">Закрыть форму</a>
				<button type="button" class="btn btn-default" data-dismiss="modal">Продолжить работу</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?php if(in_array('del', $allowedActions)): ?>
<div class="modal fade" tabindex="-1" role="dialog" id="ConfirmDelete">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Удалить страницу <b><?=$page->name?></b>?</h4>
			</div>
			<div class="modal-body">
				<p>Вы уверены, что хотите удалить страницу <b><?=$page->name?></b>?</p>
				<p>Страница будет перемещена в корзину!</p>
			</div>
			<div class="modal-footer">
				<form id="del" method="post" action="<?=$this->url('pages', array('action'=>'del', 'id'=>$page->id))?>">
					<button type="submit" class="btn btn-danger">Удалить</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Отменить</button>
				</form>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php endif;?>