<section class="block b-form">
	<header class="head">
	<h1>Редактирование категории дохода</h1>
	</header>
	<div class="body">

	<?php
	$form = $this->form;
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	?>
	<div class="form_element">
		<?=$this->formRow($form->get('name'))?>
	</div>
	<div class="form_element">
		<?=$this->formRow($form->get('color'))?>
	</div>
	<div class="form_element button">
		<?=$this->formRow($form->get('submit'))?>
	</div>
	<?php echo $this->form()->closeTag(); ?>
	<div class="clear"></div>
	</div>
</section>