<h1 class="page-header"><?=$title?></h1>

<?php
$form->prepare();
$form->setAttribute('class', 'form-horizontal')->setAttribute('role', 'form');
echo $this->form()->openTag($form);
?>	
	<?php echo $this->message($message, $is_success); ?>
		
	<div class="col-lg-6"></div>
	<div class="col-lg-6">
		<div class="form-group">
			<div class="checkbox padding-left-20 col-sm-offset-5 col-md-offset-3 col-lg-offset-5">
				<label class="">
				<?php 
					echo $this->formElement($form->get('is_active'));
					echo $form->get('is_active')->getLabel();
				?>
				</label>
			</div>
		</div>
	</div>
	
	<div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('label'));?>
	</div>
	<div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('name'));?>
	</div>
	
	<div class="clearfix"></div>
	<div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('description'));?>
	</div>

	<div class="clearfix"></div>
	
	<?=$this->partial('pages/page/permissions.phtml', array('group'=>$form->get('group'), 'permissions'=>$form->get('permissions')));?>
	
    <div class="clearfix"></div>
    
    <div class="tree">
        <h3>
			Пункты меню
			<a href="<?=$this->url("menu", array('action'=>'addItem', 'id'=>$menu->id));?>" class="btn btn-primary pull-right">
				<span class="glyphicon glyphicon-plus"></span>
				Добавить
			</a>
		</h3>
		
        <?php echo $this->partial('menu/menu/tree.phtml', array('tree'=>$tree, 'collection'=>$form->get('items')));?>
    </div>
    
    <script>
        $(function() {
            $( ".tree ul" ).sortable({
                connectWith: ".connectedSortable",
                placeholder: "placeholder",
                update: function(event, ui){
                    if(ui.sender){
                        var parentId = $(this).parent().find('>.id').val() || 0;
                        ui.item.find('.parentId').val(parentId);
                    }
                },
                stop: function(event, ui){
                    recalcPosition($('.tree'));    
                }
            }).disableSelection();
        });
        
        function recalcPosition($parent)
        {
            var $li = $parent.find('>ul>li');
            if($li.length>0)
            {
                $li.each(function(i){
                    $(this).find('.ord').val(i*10);
                    recalcPosition($(this));
                });
            }
        }
    </script>
    
	<div class="clearfix visible-lg-block"></div>
	<div class="form-group-fixed col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
		<div class="pull-right">
			<button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#ConfirmCancel" >Отменить</button>
			<?php 
				$form->get('submit')->setAttribute('class','btn btn-primary btn-lg');
				echo $this->formElement($form->get('submit'));
			?>
		</div>
	</div>
</form>	

<div class="modal fade" tabindex="-1" role="dialog" id="ConfirmCancel">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Вы уверены?</h4>
			</div>
			<div class="modal-body">
				<p>Вы уверены, что хотите закрыть форму? Несохранённые данные будут потеряны!</p>
			</div>
			<div class="modal-footer">
				<a href="<?=$referer?>" class="btn btn-danger">Закрыть форму</a>
				<button type="button" class="btn btn-default" data-dismiss="modal">Продолжить работу</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?php if(in_array('del', $allowedActions)): ?>
<div class="modal fade" tabindex="-1" role="dialog" id="ConfirmDelete">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Удалить меню <b><?=$menu->name?></b>?</h4>
			</div>
			<div class="modal-body">
				<p>Вы уверены, что хотите удалить меню <b><?=$menu->name?></b>?</p>
				<p>Все данные, связанные с меню будут удалены безвозвратно!</p>
			</div>
			<div class="modal-footer">
				<form id="deleteMenu" method="post" action="<?=$this->url('menu', array('action'=>'del', 'id'=>$menu->id))?>">
					<button type="submit" class="btn btn-danger">Удалить</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Отменить</button>
				</form>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php endif;?>