<h1 class="page-header"><?=$title?></h1>

<?php
$form->prepare();
$form->setAttribute('class', 'form-horizontal')->setAttribute('role', 'form');
echo $this->form()->openTag($form);
?>	
	<?php echo $this->message($message, $is_success); ?>
		
	<div class="col-lg-6"></div>
	<div class="col-lg-6">
		<div class="form-group">
			<div class="checkbox padding-left-20 col-sm-offset-5 col-md-offset-3 col-lg-offset-5">
				<label class="">
				<?php 
					echo $this->formElement($form->get('is_active'));
					echo $form->get('is_active')->getLabel();
				?>
				</label>
			</div>
		</div>
	</div>
	
	<div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('label'));?>
	</div>
	<div class="col-lg-6">
		<div class="form-group">
			<div class="checkbox padding-left-20 col-sm-offset-5 col-md-offset-3 col-lg-offset-5">
				<label class="">
				<?php 
					echo $this->formElement($form->get('blank'));
					echo $form->get('blank')->getLabel();
				?>
				</label>
			</div>
		</div>
	</div>
<div class="clearfix"></div>
<hr>
	<div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('type'));?>
	</div>
	<div class="col-lg-6"></div>
<div class="clearfix"></div>

	<div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('page'));?>
	</div>
	<div class="col-lg-6"></div>
	
	<div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('uri'));?>
	</div>
	<div class="col-lg-6"></div>
<div class="clearfix"></div>
<hr>

	
	<div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('icon_class'));?>
	</div>
	<?php
	/*
    <div class="col-lg-6">
		<?php echo $this->formGroup()
			->setLabelAttributes(array('class'=>'control-label col-sm-5 col-md-3 col-lg-5'))
			->setInputGroupAttributes(array('class'=>'col-sm-7 col-md-6 col-lg-7'))
			->render($form->get('icon_img'));?>
	</div>
 	*/
	?>
	
	
	<div class="clearfix visible-lg-block"></div>
	<div class="form-group-fixed col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
		<div class="pull-right">
			<button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#ConfirmCancel" >Отменить</button>
			<?php 
				$form->get('submit')->setAttribute('class','btn btn-primary btn-lg');
				echo $this->formElement($form->get('submit'));
			?>
		</div>
	</div>
</form>	

<div class="modal fade" tabindex="-1" role="dialog" id="ConfirmCancel">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Закрыть форму?</h4>
			</div>
			<div class="modal-body">
				<p>Вы уверены, что хотите закрыть форму? Несохранённые данные будут потеряны!</p>
			</div>
			<div class="modal-footer">
				<a href="<?=$referer?>" class="btn btn-danger">Закрыть форму</a>
				<button type="button" class="btn btn-default" data-dismiss="modal">Продолжить работу</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal --> 