<?php echo $this->doctype(); ?>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="favicon.ico">

	<title><?=$this->title?></title>

	<link href="<?=$this->basePath()?>/css/admin/libs.min.css" rel="stylesheet">
	<link href="<?=$this->basePath()?>/css/admin/main.min.css" rel="stylesheet">
	<link href="<?=$this->basePath()?>/css/admin/theme.min.css" rel="stylesheet">

    <script src="<?=$this->basePath()?>/js/external/jquery-3.1.1.min.js"></script>
    <script src="<?=$this->basePath()?>/js/external/angular.js"></script>
    <script src="<?=$this->basePath()?>/js/external/bootstrap.min.js"></script>
</head>

<body>
<div id="wrapper">
	<div id="alerts">
		<!--
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">×</span>
			</button>
			<strong>Ваш пароль устарел!</strong>
			Пожалуйста, смените ваш пароль до <strong>20.02.2017г.</strong>
			<a href="#" class="btn btn-danger">Сменить сейчас</a>

		</div>
		<div class="alert alert-warning alert-dismissible fade in" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">×</span>
			</button>
			<strong>Holy guacamole!</strong>
			Best check yo self, you're not looking too good.
		</div>
		-->
	</div>
	<?=$this->UserHelper()->loginAsUser('users/user-helper/login_as_user');?>
	<div id="navbar" class="col-sm-12">
		<div class="navbar-header col-md-2 col-sm-1 col-xs-12">
			<div id="logo">
				<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="IWI" class="col-md-2 col-sm-1"/>
				<span class="navbar-brand">Intelligent Web Interface</span>
			</div>
			<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".nav-target" aria-expanded="false" aria-controls="navbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="navbar-body col-md-10 col-sm-11 col-xs-12 nav-target">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<?php echo $this->AuthHelper()->user('auth/authHelper/user', 'auth/authHelper/guest'); ?>

				</li>
			</ul>
			<ul class="nav navbar-nav">
				<li><a href="#"><span class="glyphicon glyphicon-th"></span><span
							class="text">Рабочий стол</span></a>
				</li>

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<span class="glyphicon glyphicon-star"></span><span
							class="text">Избранное</span><span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<a href="#">Page 1</a>
						</li>
						<li>
							<a href="#">Page 2</a>
						</li>
						<li>
							<a href="#">Page 3</a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-star-empty"></span>Добавить в избранное</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="#">
						<span class="glyphicon glyphicon-bell"></span>
						<span class="text">Уведомления</span>
						<span id="notif-count" class="count">10</span>
					</a>
				</li>

				<li><a href="#"><span class="glyphicon glyphicon-question-sign"></span><span
							class="text">Помощь</span></a></li>
			</ul>
		</div>
	</div>

	<div id="sidebar" class="col-md-2 col-sm-1 col-xs-12 nav-target">
		<?php echo $this->MenuHelper('test')->setPartial('menu/menuHelper/nav-sidebar')->render(); ?>
		<?php echo $this->MenuHelper('capital')->setPartial('menu/menuHelper/nav-sidebar')->render(); ?>
		<?php echo $this->MenuHelper('admin')->setPartial('menu/menuHelper/nav-sidebar')->render(); ?>
	</div>

	<div id="sidebar-footer" class="col-md-2 col-sm-1 col-xs-12 nav-target">
		sidebar-footer
	</div>


	<div id="main" class="col-md-10 col-sm-11 col-xs-12">
		<?=$this->content; ?>
	</div>

	<div id="empty" class=""></div>
</div>
<div id="footer">
	<div class="col-sm-1 col-md-2 col-xs-12 sidebar-footer-place"></div>
	<div class="col-sm-11 col-md-10 footer-content">footer</div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="<?=$this->basePath()?>/js/libs.min.js"></script>
<script src="<?=$this->basePath()?>/js/classes.min.js"></script>
<script src="<?=$this->basePath()?>/js/modules.min.js"></script>
<script src="<?=$this->basePath()?>/js/init.min.js"></script>
<?php echo $this->AuthHelper()->timeoutScript(); ?>

</body>
</html>
