<?php echo $this->doctype(); ?>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Mikhail Khapchik">
    <link rel="icon" href="favicon.ico">

    <title><?=$this->title?></title>

    <!-- Bootstrap core CSS -->
    <link href="<?=$this->basePath()?>/css/bootstrap.min.css" rel="stylesheet">
	
	<!-- Jquery ui core CSS -->
    <link href="<?=$this->basePath()?>/css/jquery-ui.css" rel="stylesheet">
	
	<!-- Jquery ui datetimepicker core CSS -->
    <link href="<?=$this->basePath()?>/css/jquery.datetimepicker.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="<?=$this->basePath()?>/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?=$this->basePath()?>/css/dashboard.css" rel="stylesheet">
	
	<link href="<?=$this->basePath()?>/css/custom.css" rel="stylesheet">

   	
	
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?=$this->basePath()?>/js/lib/jquery-2.1.3.min.js"></script>
    <script src="<?=$this->basePath()?>/js/lib/bootstrap.min.js"></script>
	
	<script src="<?=$this->basePath()?>/js/lib/jquery-ui.min.js"></script>
	
	<script src="<?=$this->basePath()?>/js/lib/jquery.datetimepicker.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/modalDialog.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/dynamic-element.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/dynamic-select.js"></script>
	
	<script src="<?=$this->basePath()?>/js/lib/jquery.form.min.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/form.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/loader.js"></script>
	
	<script src="<?=$this->basePath()?>/js/lib/flot/jquery.flot.min.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/flot/jquery.flot.time.min.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/flot/jquery.flot.selection.min.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/flot/jquery.flot.resize.min.js"></script>
	<script src="<?=$this->basePath()?>/js/lib/flot/jquery.flot.navigate.min.js"></script>
    
	<!-- Just to make our placeholder images work. Don't actually copy the next line! 
    <script src="../../assets/js/vendor/holder.min.js"></script>
	-->
	
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="<?=$this->basePath()?>/js/lib/ie10-viewport-bug-workaround.js"></script>
	
	<script src="<?=$this->basePath()?>/js/init.js"></script>
	
  </head>

  <body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<a class="navbar-brand navbar-left" href="#">
			<!--
            <img alt="IWI" src="../img/logo.png" height="50">
            -->
            <svg height="50" width="150">
              <text x="10" y="43" fill="#fff" stroke="#000" stroke-width="0.5" font-size="50px" font-weight="bold">IWI</text>
              IWI
            </svg>
            
		</a>
		<div class="navbar-right">
			<?php echo $this->AuthHelper()->user('auth/authHelper/user', 'auth/authHelper/guest'); ?>
		</div>
		
		<div class="navbar-header navbar-left">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar_menu" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		</div>
		
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="navbar-right" id="top_menu">
		  <ul class="nav navbar-nav">
			<li><a href="#">Link1Link1</a></li>
			<li class="dropdown">
			  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Link2Link2 <span class="caret"></span></a>
			  <ul class="dropdown-menu">
				<li><a href="#">Action</a></li>
				<li><a href="#">Another action</a></li>
				<li><a href="#">Something else here</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="#">Separated link</a></li>
			  </ul>
			</li>
			<li><a href="#">Link3Link3</a></li>

		  </ul>
		</div><!-- /.navbar-collapse -->
		
	  </div><!-- /.container-fluid -->
	</nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar" id="sidebar_menu">
    
			<?php echo $this->MenuHelper('test')->setPartial('menu/menuHelper/nav-sidebar')->render(); ?>	
			<?php echo $this->MenuHelper('capital')->setPartial('menu/menuHelper/nav-sidebar')->render(); ?>	
			<?php echo $this->MenuHelper('admin')->setPartial('menu/menuHelper/nav-sidebar')->render(); ?>
		  
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<?=$this->UserHelper()->loginAsUser('users/user-helper/login_as_user');?>
			<?=$this->content; ?>
        </div>
      </div>
    </div>

	<?php echo $this->AuthHelper()->timeoutScript(); ?>
  </body>
</html>