<h1 class="page-header"><?=$title?></h1>

<?php
	$form->prepare();
	$form->setAttribute('class', 'form-horizontal')
		->setAttribute('role', 'form')
		->setAttribute('id', 'role_form');
	echo $this->form()->openTag($form);
?>
	<div class="col-lg-8">
		<?php echo $this->partial('users/roles-manager/form-inside.phtml', array('form'=>$form, 'message'=>$message, 'is_success'=>$is_success)); ?>
	</div>

	<div class="clearfix visible-lg-block"></div>
	<div class="form-group-fixed col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
		<?php if($can_delete): ?>
			<div class="pull-left">
				<button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#ConfirmDelete" >Удалить</button>
			</div>
		<?php endif;?>
		<div class="pull-right">
			<button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#ConfirmCancel" >Отменить</button>
			<?php
			$form->get('submit')->setAttribute('class','btn btn-primary btn-lg');
			echo $this->formElement($form->get('submit'));
			?>
		</div>
	</div>

<?php
	echo $this->form()->closeTag();
?>

