<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?=$title?></h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <?php
                $form->prepare();
                $form->setAttribute('class', 'form-horizontal')
                    ->setAttribute('role', 'form')
                    ->setAttribute('id', 'role_form');
                echo $this->form()->openTag($form);
                echo $this->partial('users/roles-manager/form-inside.phtml', array('form'=>$form, 'message'=>$message, 'is_success'=>$is_success));
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
            <button name="submit" class="btn btn-primary submitModal">
                <?=$form->get('submit')->getValue()?>
            </button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->